services:
  mysql:
    container_name: mysql_container
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
    volumes:
      - mysql_data:/var/lib/mysql

  server:
    container_name: server_container
    image: nayoun340/naejeonhaja
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - redis  # Redis에 대한 의존성 추가
    restart: always
    volumes:
      - ./logs:/logs  # 호스트의 logs 디렉터리와 컨테이너의 /logs 디렉터리 연결
    env_file:
      - .env  # .env 파일을 읽어서 환경 변수로 전달
    environment:
      - SPRING_PROFILES_ACTIVE=prd

  redis:
    container_name: redis_container
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    restart: always  # Redis 컨테이너가 중지된 경우 자동 재시작

volumes:
  mysql_data:
  redis_data:
