services:
  mysql:
    container_name: mysql_container
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
    volumes:
      - mysql_data:/var/lib/mysql

  server:
    container_name: server_container
    image: nayoun340/naejeonhaja
    ports:
      - 8080:8080
    depends_on:
      - mysql
    restart: always
    env_file:
      - .env  # .env 파일을 읽어서 환경 변수로 전달

volumes:
  mysql_data: