spring:
  profiles:
    active: dev
  mail:
    naver:
      email: ${NAVER_EMAIL}
      password: ${NAVER_PASSWORD} # 또는 앱 비밀번호
    gmail:
      email: ${GMAIL_EMAIL}
      password: ${GMAIL_PASSWORD} # 또는 앱 비밀번호
    kakao:
      email: ${KAKAO_EMAIL}
      password: ${KAKAO_PASSWORD} # 또는 앱 비밀번호

# JWT
jwt:
  secret:
    key: ${JWT_SECRET_KEY}

# Riot
riot:
  api:
    key: ${RIOT_API_KEY}

# Swagger
springdoc:
  swagger-ui:
    path: /docs
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
