name: 'CD'

on:
  push:
    branches: [ main ]

jobs:
  cd:
    runs-on: self-hosted
    steps:
      - name: 깃헙 코드를 VM으로 복사
        uses: actions/checkout@v4

      - name: 깃헙 액션의 VM에 자바 설치중 ...
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      # 여기서 복사 시킬떄 compose.yml파일이랑 env파일을 둘이 같은 위치에 두게한다음에  해야할듯
      - name: ENV 복사
        run: |
          echo "${{ secrets.ENV }}" > .env
        shell: bash

      - name: 빌드 및 테스트 코드 돌리는중 ...
        run: |
          chmod +x ./gradlew
          ./gradlew build -x test

      - name: 도커 이미지 빌드 및 푸시
        run: |
          docker login -u ${{secrets.DOCKER_ID}} -p ${{secrets.DOCKER_TOKEN}}
          docker build -t ${{secrets.DOCKER_ID}}/${{secrets.DOCKER_REPO}} .
          docker push ${{secrets.DOCKER_ID}}/${{secrets.DOCKER_REPO}}

      - name: 배포할 로컬컴퓨터에 yml 파일 옮기기
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{secrets.LOCAL_IP}}
          key : ${{secrets.LOCAL_KEY}}
          username: ${{secrets.LOCAL_USERNAME}}
          source: ./docker-compose.yml
          target: ~/

      - name: 배포할 로컬컴퓨터에 env 파일 옮기기 (yml 파일과 동일한 위치)
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{secrets.LOCAL_IP}}
          key: ${{secrets.LOCAL_KEY}}
          username: ${{secrets.LOCAL_USERNAME}}
          source: .env
          target: ~/

      - name: 배포할 로컬컴퓨터 내부에서 docker-compose 실행시키기
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.LOCAL_IP}}
          key: ${{secrets.LOCAL_KEY}}
          username: ${{secrets.LOCAL_USERNAME}}
          script: |            
            cd ~/
            docker-compose down
            docker-compose pull 
            docker-compose up --build -d
            docker cp .env server_container:/app/.env
            docker image prune -f          
            
          
            
