name: 'CI_CD'

on:
  pull_request:
    branches: [ main ]

jobs:
  cicd:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: 깃헙 코드를 VM으로 복사
        uses: actions/checkout@v4

      - name: 깃헙 액션의 VM에 자바 설치중 ...
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: env 파일 생성
        run: |
          echo "${{ secrets.LOCAL_ENV }}" > .env
        shell: bash

      - name: MySQL 도커 컨테이너 실행
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: ${MYSQL_DB_NAME}
          mysql root password: ${MYSQL_PASSWORD}

      - name: 빌드 및 테스트 코드 돌리는중 ...
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: 도커 이미지 빌드 및 푸시
        run: |
          docker login -u ${{secrets.DOCKER_ID}} -p ${{secrets.DOCKER_TOKEN}}
          docker build -t ${{secrets.DOCKER_ID}}/${{secrets.DOCKER_REPO}} .
          docker push ${{secrets.DOCKER_ID}}/${{secrets.DOCKER_REPO}}