# .github/workflows/main.yml
name: AI Code Reviewer

on:
  pull_request:
    branches: [ dev ]
    types:
      - opened
      - synchronize

permissions: write-all

jobs:
  review:
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true
      ACTIONS_RUNNER_DEBUG: true
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run AI Code Reviewer
        uses: kkm4512/ai-code-reviewer@main
        with:
          GITHUB_TOKEN: ${{ secrets.KKM_GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          COMMENT_LANGUAGE: "ko-KR"
          OPENAI_API_MODEL: "gpt-4o-mini"
          exclude: "**/*.json, **/*.md"